[package]
name = "text-mutator"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
axum = "0.8.3"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.6.1", features = ["cors"] }