name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the backend
        run: cargo build --verbose --manifest-path backend/Cargo.toml

      - name: Test the backend
        run: cargo test --verbose --manifest-path backend/Cargo.toml

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 23
          cache: "npm"
          cache-dependency-path: "frontend/package.json"

      - name: Build the frontend
        run: npm --prefix frontend ci

      - name: Test the frontend
        run: npm run --prefix frontend test

  deploy:
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Log in to Azure
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

          # TODO
          # Push the rust image to ACR
          # Push the frontend to Azure static apps
